builders:
  masamune_module_builder:
    import: 'package:katana_module_builder/katana_module_builder.dart'
    builder_factories: ['masamuneModuleBuilderFactory']
    build_extensions: {'.dart': ['.m.dart']}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
targets:
  $default:
    builders:
      masamune_module_builder:
        enabled: true
        generate_for:
          exclude:
            - test
            - example
          include:
            - test/integration/*
            - test/integration/**/*